<?php

namespace AppBundle\Repository;

/**
 * category_locationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class category_locationRepository extends \Doctrine\ORM\EntityRepository
{
}
