<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function getAllMeetingsOfUser(User $user)
    {
        $userGroups = $user->getGroups();
        $meetings = [];

        foreach ($userGroups as $userGroup)
        {
            $group_id = $userGroup->getId();
            $em = $this->getEntityManager();
            $qb = $em->createQueryBuilder();

            $qb->select('u')
                ->from('AppBundle:Meeting', 'u')
                ->where('u.group = :identifier')
                ->setParameter('identifier', $userGroup);

            $query = $qb->getQuery();

            $meetings[] = $query->getResult();
                        //$query->getArrayResult();
        }

        return $meetings;
    }
}
