# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt
      Symfony\Component\Security\Core\User\User:
                  algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/city/add, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }